# -*- coding: utf-8 -*-
"""Data Engineering project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kvab53_3Rwl6L_Y7M2gsU9-W3bHHzCzV

---
Import Libraries

---
"""

# Data Processing
import pandas as pd
import numpy as np

# Database
import sqlite3

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

"""---
Data Ingestion

---
"""

# Sample Customer Data
data = {
    "CustomerID": [101, 102, 103, 104, 105],
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Age": [25, 30, np.nan, 45, 35],
    "City": ["New York", "Los Angeles", "Chicago", "Houston", np.nan],
    "PurchaseAmount": [250, 300, 150, 400, 500]
}

df = pd.DataFrame(data)
print("Raw Data:\n", df)

"""---
Data Cleaning

---
"""

# Fill missing Age with mean
df['Age'].fillna(df['Age'].mean(), inplace=True)

# Fill missing City with 'Unknown'
df['City'].fillna('Unknown', inplace=True)

# Convert PurchaseAmount to float
df['PurchaseAmount'] = df['PurchaseAmount'].astype(float)

print("Cleaned Data:\n", df)

"""---
Data Transformation

---
"""

def segment(amount):
    if amount < 200:
        return 'Low'
    elif amount < 400:
        return 'Medium'
    else:
        return 'High'

df['CustomerSegment'] = df['PurchaseAmount'].apply(segment)
print("Transformed Data:\n", df)

"""---
Store Data in SQLite Database

---
"""

# Connect to SQLite database (creates if not exist)
conn = sqlite3.connect('customer_data.db')

# Store the data
df.to_sql('customers', conn, if_exists='replace', index=False)

# Verify by reading back
df_db = pd.read_sql('SELECT * FROM customers', conn)
print("Data from Database:\n", df_db)

"""---
Basic Analysis & Visualization

---
"""

# PurchaseAmount by Segment
sns.barplot(x='CustomerSegment', y='PurchaseAmount', data=df)
plt.title("Purchase Amount by Customer Segment")
plt.show()

# Count of customers per city
city_counts = df['City'].value_counts()
city_counts.plot(kind='bar', title='Customers per City')
plt.show()